export const ActionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST: ' REMOVE_FROM_WISHLIST',
    ADD_ADDRESS: 'ADD_ADDRESS',
    DELETE_ADDRESS: 'DELETE_ADDRESS'
};